version: 2.1


orbs:
    python: circleci/python@1.4.0
    cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
    build_stage:
        working_directory: ~/currency-converter
        docker:
            - image: 'cimg/python:3.9.5'
        steps:
            - checkout
            - run:
                working_directory: backend
                command: pip install -r requirements.txt
    
    testing_stage:
        docker:
            - image: 'cimg/python:3.9.5'
        steps:
            - checkout
            - run:
                working_directory: backend
                command: pip install -r requirements.txt
            - run:
                working_directory: backend
                command: pytest

    release_stage:
        docker:
            - image: 'cimg/base:stable'
        steps:
            - checkout
            - cloud-run/init
            - cloud-run/build:
                tag: 'asia.gcr.io/${GOOGLE_PROJECT_ID}/currency-converter'

workflows:
    version: 2
    sairyo_no_workflow:
        jobs:
            - release_stage

        