version: 2.1

orbs:
    python: circleci/python@1.4.0
    cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
    build_stage:
        working_directory: ~/currency-converter
        docker:
            - image: 'cimg/python:3.9.5'
        steps:
            - checkout
            - run:
                working_directory: backend
                command: pip install -r requirements.txt
    
    testing_stage:
        docker:
            - image: 'cimg/python:3.9.5'
        steps:
            - checkout
            - run:
                working_directory: backend
                command: pip install -r requirements.txt
            - run:
                working_directory: backend
                command: pytest

    release_stage:
        docker:
            - image: 'cimg/base:stable'
        steps:
            - checkout
            - cloud-run/init
            - cloud-run/build:
                tag: 'asia.gcr.io/${GOOGLE_PROJECT_ID}/currency-converter'

    deploy_stage:
        docker:
            - image: 'cimg/base:stable'
        steps:
            - checkout
            - cloud-run/init
            - cloud-run/deploy:
                image: 'asia.gcr.io/${GOOGLE_PROJECT_ID}/currency-converter:latest'
                platform: managed
                region: asia-south1
                service-name: currency-converter
                unauthenticated: true

workflows:
    version: 2
    deploy_workflow:
        jobs:
            - build_stage
                filters:
                    branches:
                        only:
                            - main
            - testing_stage:
                filters:
                    branches:
                        only:
                            - main
                requires:
                    - build_stage
            - approval_stage:
                filters:
                    branches:
                        only:
                            - main
                type: approval
                requires:
                    - testing_stage
            - release_stage:
                filters:
                    branches:
                        only:
                            - main
                requires:
                    - approval_stage
            - deploy_stage:
                filters:
                    branches:
                        only:
                            - main
                requires:
                    - release_stage
    testing_workflow:
        jobs:
            - build_stage
                filters:
                    branches:
                        ignore:
                            - main
            - testing_stage:
                filters:
                    branches:
                        ignore:
                            - main
                requires:
                    - build_stage
        